### ISSUE TITLE
implement check .reg

### ISSUE THREAD

**Issue by Obstkuchen3000** [rngShard/dsa-discord-bot#10]
implement a check, that rolls on LeP regeneration, KeP regeneration and AsP regeneration considering special skills like regeneration 1,2,3 and so on

**Comment by rescuehero** [comment]
need SF and categorized advantages in charactersheet - anyone can add this? @Obstkuchen3000 @rngShard 

the more standardized it is, the easier to implement regeneration.

is adding all possible SF's, advantages, disadvanteges as int (0-20) like in the excel-sheet a good idea or even implemented yet?

**Comment by rngShard** [comment]
Probably easiest to implement w6 + KO w20 check for LE and w6 + IN w20 for AsP with flexible mods?

When allowing basic Regeneration SFs, advantages etc. we'd increase the complexity, but simple regeneration with basic mods should do the trick as well initially , what you think?

**Comment by rescuehero** [comment]
done.

todo: add SF's/advantages in future?
