### ISSUE TITLE
Critical Success / Failure should not display "Result value" in output

### ISSUE THREAD

**Issue by rngShard** [rngShard/dsa-discord-bot#14]
![image](https://user-images.githubusercontent.com/11741104/80872834-c710f280-8cb4-11ea-83cf-502d680b6b6a.png)
![image](https://user-images.githubusercontent.com/11741104/80872843-d98b2c00-8cb4-11ea-9e64-c69edbadc5c9.png)
![image](https://user-images.githubusercontent.com/11741104/80872845-dd1eb300-8cb4-11ea-80e0-b3073e547b5c.png)

**Comment by rescuehero** [comment]
closed because of double...
again!

see #11 and #12
