### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by ZsadistWoW** [rngShard/dsa-discord-bot#5]
FICK DICH GITHUB DAS IST EIN TEST - sorry ich habe ein kleines aggressionsproblem

**Comment by rngShard** [comment]
Sure you want this fixed?

**Comment by ZsadistWoW** [comment]
> 
> 
> Sure you want this fixed?

YES PLEASE

**Comment by ZsadistWoW** [comment]
> 
> 
> > Sure you want this fixed?
> 
> YES PLEASE

BITTE BEHEBEN SIE MEINE AGGRESSIONEN
